name: Home Manager
main: com.github.SaxSalute.HomeManager.HomeManager
version: 1

commands:
    createhome:
        description: Used to create and homes
        usage: /createhome [home name]
        permission: HomeManager.createhome
        permission-message: You don't have <permission>
    deletehome:
        description: Used to delete homes
        usage: /deletehome [home name]
        permission: HomeManager.deletehome
        permission-message: You don't have <permission>
    addbuilder:
        description: Used to add builders to homes
        usage: /addbuilder [builder name] [home name]
        permission: HomeManager.addbuilder
        permission-message: You don't have <permission>