name: Home Manager
main: com.github.SaxSalute.HomeManager.HomeManager
version: 1

commands:
    createhome:
        description: Used to create and homes
        usage: /createhome [home name]
        permission: HomeManager.createhome
        permission-message: You don't have <permission>
    deletehome:
        description: Used to delete homes
        usage: /deletehome [home name]
        permission: HomeManager.deletehome
        permission-message: You don't have <permission>
    addbuilder:
        description: Used to add builders to homes
        usage: /addbuilder [builder name] [home name]
        permission: HomeManager.addbuilder
        permission-message: You don't have <permission>
        
permissions:
    HomeManager.*:
        description: Gives access to all of the HomeManager commands
        children:
            HomeManager.createhome: true
            HomeManager.deletehome: true
            HomeManager.addbuilder: true
    HomeManager.createhome:
        description: Allows a user to create homes
        default: op
    HomeManager.deletehome:
        description: Allows a user to delete homes
        default: op
    HomeManager.addbuilder:
        description: Allows a user to add builders to homes which they own
        default: true